name: Release

on:
  pull_request:
    branches:
      - main
      - '!develop'
      - '!feature/**'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')" 
    - name: Publish Unix version
      run: dotnet publish -c Release -r linux-x64 --self-contained true -o ./rel-linux ./src/HttpExecutor/HttpExecutor.csproj
    - name: Zip linux version
      run: |
        tar -zcvf httprun-${{ steps.date.outputs.date }}-linux.tar.gz rel-linux/
    - name: Publish Windows version
      run: dotnet publish -c Release -r win-x64 --self-contained true -o ./rel-win ./src/HttpExecutor/HttpExecutor.csproj
    - name: Zip Windows version
      run: |
        zip -r httprun-${{ steps.date.outputs.date }}-win64.zip --junk-paths rel-win/*
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.date.outputs.date }}
        tag_name: ver-${{ github.sha }}
        body: Release of httprun
      env:
        GITHUB_TOKEN: ${{ github.token }}  
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: httprun-${{ steps.date.outputs.date }}-linux.tar.gz
        asset_name: httprun-${{ steps.date.outputs.date }}-linux.tar.gz
        asset_content_type: application/gzip 
    - name: upload Windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: httprun-${{ steps.date.outputs.date }}-win64.zip
        asset_name: httprun-${{ steps.date.outputs.date }}-win64.zip
        asset_content_type: application/zip         
